### ISSUE TITLE
Wildcard for all namespaces?

### ISSUE THREAD

**Issue by sc250024** [EmberStack/ES.Kubernetes.Reflector#7]
Greetings,

I was wondering for the `cert-manager` plugin if it's possible to do something like this:

```yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed-namespaces: "*"
    reflector.v1.k8s.emberstack.com/secret-reflection-allowed: "true"
```

Specifically, does the `reflector.v1.k8s.emberstack.com/secret-reflection-allowed-namespaces` annotation support the `*` wildcard for **all** namespaces?

Thank you!
